FROM docker.io/library/ubuntu AS base
ENV HOME /root
RUN apt-get update
RUN apt-get install -y \
        git \
        wget \
        flex \
        bison \
        gperf \
        python3 \
        python3-pip \
        python3-venv \
        cmake \
        ninja-build \
        ccache \
        libffi-dev \
        libssl-dev \
        dfu-util \
        libusb-1.0-0 \
        tree
RUN git clone -b v5.1.2 --recursive https://github.com/espressif/esp-idf.git "${HOME}/esp-idf"
RUN ${HOME}/esp-idf/install.sh
RUN mkdir -p \
    "${HOME}/micropython" \
    "${HOME}/src" \
    "${HOME}/output" \
    "${HOME}/merged"
COPY --chmod=0777 "mount-setup.sh" "${HOME}/"

FROM base AS root-make
WORKDIR /root
COPY --chmod=0777 "entrypoint-root-make.sh" "./"
ENTRYPOINT ["./entrypoint-root-make.sh"]

FROM base AS esp32-make
WORKDIR /root
COPY --chmod=0777 "entrypoint-esp32-make.sh" "./"
ENTRYPOINT ["./entrypoint-esp32-make.sh"]
